CREATE TABLE clients(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE employees(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL
);

CREATE TABLE projects(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL
);

ALTER TABLE employees
ADD COLUMN project_id INT REFERENCES projects(id);

ALTER TABLE projects
ADD COLUMN client_id INT REFERENCES clients(id),
ADD COLUMN project_lead_id INT REFERENCES employees(id)
